name: 打包项目
on: push

permissions:
  contents: write

jobs:
  pnpm-build:
    name: pnpm-build工作
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 安装pnpm
      uses: pnpm/action-setup@v3
      with:
        version: next-9
        standalone: true

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    - name: 安装依赖+项目打包
      run: |
        pnpm install
        pnpm run build

    - name: 项目部署
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist
